const DIFFICULTY = 3;
const MINE_RATE = 30000;
const INITIAL_BALANCE = 10;
const FIRST_MINING_REWARD = 50;
const BLOCKCHAIN_WALLET = 'Blockchain wallet';
const MINER_WALLET = 'Miner';
const MAXIMUM_INBOUNDS = 40;
const MAXIMUM_OUTBOUNDS = 8;
const P2P_SOCKET_RECONNECTION_RETRIES = 10;

module.exports = {
  DIFFICULTY,
  MINE_RATE,
  INITIAL_BALANCE,
  FIRST_MINING_REWARD,
  BLOCKCHAIN_WALLET,
  MINER_WALLET,
  MAXIMUM_INBOUNDS,
  MAXIMUM_OUTBOUNDS,
  P2P_SOCKET_RECONNECTION_RETRIES,
};
