const DIFFICULTY = 2;
const MINE_RATE = 30000;
const INITIAL_BALANCE = 20;
const FIRST_MINING_REWARD = 50;
const BLOCKCHAIN_WALLET = 'Blockchain wallet';
const MINER_WALLET = 'Miner';
const MAXIMUM_INBOUNDS = 40;
const MAXIMUM_OUTBOUNDS = 40;
const P2P_SOCKET_RECONNECTION_RETRIES = 10;
// in ms
const P2P_SOCKET_RECONNECTION_INTERVAL = 2000;

module.exports = {
  DIFFICULTY,
  MINE_RATE,
  INITIAL_BALANCE,
  FIRST_MINING_REWARD,
  BLOCKCHAIN_WALLET,
  MINER_WALLET,
  MAXIMUM_INBOUNDS,
  MAXIMUM_OUTBOUNDS,
  P2P_SOCKET_RECONNECTION_RETRIES,
  P2P_SOCKET_RECONNECTION_INTERVAL,
};
